2019-11-11 17:27:36,078 ERROR: Exception on /index [POST] [in c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "c:\Users\jrpete\Projects\microblog\microblog-0.15\app\main\routes.py", line 28, in index
    language = guess_language(form.post.data)
TypeError: 'module' object is not callable
2019-11-11 17:29:11,088 ERROR: Exception on /index [POST] [in c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "c:\Users\jrpete\Projects\microblog\microblog-0.15\app\main\routes.py", line 28, in index
    language = guess_language.guess_language(form.post.data)
TypeError: 'module' object is not callable
2019-11-11 17:30:20,855 ERROR: Exception on /index [POST] [in c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "c:\Users\jrpete\Projects\microblog\microblog-0.15\app\main\routes.py", line 28, in index
    language = guess_language(form.post.data)
TypeError: 'module' object is not callable
2019-11-11 17:30:36,762 ERROR: Exception on /index [POST] [in c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "c:\Users\jrpete\Projects\microblog\microblog-0.15\app\main\routes.py", line 28, in index
    language = guess_language.guessLanguage(form.post.data)
TypeError: 'module' object is not callable
2019-11-11 17:31:46,985 ERROR: Exception on /index [POST] [in c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "c:\Users\jrpete\Projects\microblog\microblog-0.15\app\main\routes.py", line 28, in index
    language = guess_language(form.post.data)
TypeError: 'module' object is not callable
2019-11-11 17:32:30,684 ERROR: Exception on /index [POST] [in c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jrpete\projects\microblog\microblog-0.15\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "c:\Users\jrpete\Projects\microblog\microblog-0.15\app\main\routes.py", line 28, in index
    language = guess_language(form.post.data)
TypeError: 'module' object is not callable
2019-11-11 17:39:40,684 INFO: Microblog startup [in c:\Users\jrpete\Projects\microblog\microblog-0.15\app\__init__.py:74]
2019-11-11 17:51:33,414 INFO: Microblog startup [in c:\Users\jrpete\Projects\microblog\microblog-0.15\app\__init__.py:74]
2019-11-11 23:38:34,592 INFO: Microblog startup [in c:\Users\jrpete\Projects\microblog\microblog-0.15\app\__init__.py:79]
2019-11-11 23:39:01,057 INFO: Microblog startup [in c:\Users\jrpete\Projects\microblog\microblog-0.15\app\__init__.py:79]
2019-11-11 23:39:21,857 INFO: Microblog startup [in c:\Users\jrpete\Projects\microblog\microblog-0.15\app\__init__.py:79]
2019-11-11 23:40:28,159 INFO: Microblog startup [in c:\Users\jrpete\Projects\microblog\microblog-0.15\app\__init__.py:79]
2019-11-11 23:42:33,331 INFO: Microblog startup [in c:\Users\jrpete\Projects\microblog\microblog-0.15\app\__init__.py:79]
